In [1]:
import numpy as np

In [2]:
import pandas as pd

In [11]:
# spilt method required same pair element 
a=np.array([1,2,3,4,56,67,8,0])  
b=np.split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([56, 67]), array([8, 0])]


In [13]:
# array_spilt method not required  pair element 
a=np.array([1,2,3,4,56,67,8])
b=np.array_split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([56, 67]), array([8])]


In [14]:
c=np.array([1,2,3,4,5,6,7,89,1,2,3,4,754,3])
v=np.where(c==2)

In [15]:
v

(array([1, 9]),)

In [16]:
z=np.array([[[1,2,3],[4,5,6]]])
b=np.where(z==4)
b

(array([0]), array([1]), array([0]))

In [36]:
s=np.sort(z)
s

array([[[1, 2, 3],
        [4, 5, 6]]])

In [17]:
q=np.array([[[[12,23,45,67],[12,23,4,45],[2,45,1,7]]]])
w=np.where(q==1)
w

(array([0]), array([0]), array([2]), array([2]))

In [18]:
e=q[w]

In [19]:
e

array([1])

In [23]:
# for i in np.nditer(q):
#     print(i)

In [22]:
r=np.where(q==45)
r

(array([0, 0, 0]), array([0, 0, 0]), array([0, 1, 2]), array([2, 3, 1]))

In [24]:
s=np.where(q==23)

In [25]:
s

(array([0, 0]), array([0, 0]), array([0, 1]), array([1, 1]))

In [31]:
f=np.where(q>34)
t=q[f]
t


array([45, 67, 45, 45])

In [33]:
y=np.where(q<34)
g=q[y]
g

array([12, 23, 12, 23,  4,  2,  1,  7])

In [34]:
a=np.sort(q)

In [35]:
a

array([[[[12, 23, 45, 67],
         [ 4, 12, 23, 45],
         [ 1,  2,  7, 45]]]])

In [37]:
a=np.array([89.6,5,45,34,2,90,0,56,4,3,2,1])
v=np.sort(a)
v

array([ 0. ,  1. ,  2. ,  2. ,  3. ,  4. ,  5. , 34. , 45. , 56. , 89.6,
       90. ])

In [38]:
z=np.array(["roshani","a","f","s","z","x"])
print(np.sort(z))

['a' 'f' 'roshani' 's' 'x' 'z']


In [52]:
n=np.array([12,2,3,45,12,3,45,6,85422,4,453,1234,351,1,1,13354,32,12,1234])
h=[]

for i in n:
    if i%2==0:
        h.append(True)
    else:
        h.append(False)

y=n[h]
y
h

[True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True]

In [ ]:

a=np.array([1,2,3,4,5,6,7,8,9,10])

b=[]

for i in a:
    if i%2==0:
        b.append(True)
    else:
        b.append(False)
    
s=a[b]
print(s)
print(b)

In [56]:
v=np.array([0,-1,-2,-3,9,5,4])
d=[]
for i in np.nditer(v):
    if i>0:
        d.append(True)
    else:
        d.append(False)
c=v[d]
c
d

[False, False, False, False, True, True, True]

In [58]:
p=np.array([1,2,3,4,566,3,3,3,6,2,1])
q=[]
for i in np.nditer(p):
    if i==3:
        q.append(True)
    else:
        q.append(False)

a=p[q]
a
q

[False, False, True, False, False, True, True, True, False, False, False]

In [67]:
# from numpy import random
x=random.randint(100)
print(x)

61


In [70]:
s=random.rand()
s

0.12436476502287674

In [71]:
v=random.randint(200,size=7)
v

array([105, 115,  24, 109, 183, 117, 110], dtype=int32)

In [72]:
b=random.randint(500,size=100)
b

array([ 46,  18, 278,  30, 165, 253, 394,  92, 317,  49, 479, 222, 100,
       483, 249, 180, 101,  77, 399,  47, 208, 111, 175, 240, 360, 156,
       422, 315, 316, 450, 374, 463,  52,  50, 249, 295, 412, 155,  25,
       291, 495,  60, 207,  76, 138, 280, 310, 200, 214, 162, 107, 358,
       359, 326, 319, 402, 139, 217, 229, 289, 424, 436, 461, 334,  55,
       374, 181, 383, 411, 357, 449,  98,  18, 357, 343, 251, 366, 295,
       478, 336,  19, 304,  72, 205, 295,  31, 329, 443, 117, 359, 298,
       205, 410,  69, 202, 387, 126, 120, 365, 169], dtype=int32)

In [73]:
v=random.randint(700,size=(5,5))
v

array([[ 81, 253, 349, 216, 233],
       [ 63, 697, 166, 273, 685],
       [216, 599, 579, 558, 507],
       [333,   9, 134, 556, 119],
       [319, 623,  55, 294,  58]], dtype=int32)

In [74]:
o=random.randint(900,size=(10,30))
o

array([[103, 481, 790, 586, 411, 899, 360, 680, 384, 670, 518,   8, 888,
        738, 638, 361, 755, 781, 624, 835, 363, 815, 211, 307, 143, 146,
        449, 415, 278, 645],
       [556, 861, 764, 745, 693, 414, 823, 801,  96, 173, 877, 259, 318,
        340, 761, 359, 721, 223, 411, 295, 620, 881,  84, 322, 883, 613,
        184, 582, 154, 221],
       [ 51, 577, 283, 183, 214, 679, 755,  43, 596,  58, 563, 729, 423,
        442, 602, 343,  11, 619, 876, 119, 525, 775, 541, 372, 488,  47,
        183, 886, 636,  64],
       [224, 530, 379, 704, 298,  82, 315, 195, 224, 462, 330, 897,  96,
        103, 416, 353, 245, 838, 707, 159, 450, 693, 847, 834, 308, 230,
        579, 331, 552, 422],
       [241, 678, 449, 704, 719, 103, 832, 527, 716, 488, 627, 281, 377,
        304, 566, 737, 563, 501, 873, 702, 366, 608, 271, 398, 519, 730,
        210,  33, 570, 683],
       [ 28, 339,  71, 338, 826, 398, 574, 419, 837, 781,  53, 601, 697,
        385, 718,  42, 790, 752,  91, 324, 161, 877,

In [75]:
f=random.rand(400)
f

array([2.25597875e-01, 9.49206597e-01, 3.52094837e-01, 2.24350528e-01,
       8.81523358e-01, 2.23653079e-01, 9.17265035e-01, 5.89603647e-01,
       8.86863527e-01, 3.57230861e-01, 1.28634174e-01, 4.80204115e-01,
       9.93969173e-01, 5.04346041e-01, 1.22128380e-01, 2.24083156e-02,
       9.30022524e-01, 1.40510637e-01, 5.61326900e-01, 9.85261789e-01,
       1.84329383e-01, 1.68878694e-01, 4.40237493e-01, 3.49776932e-01,
       2.50275794e-01, 1.57338311e-01, 9.25947002e-01, 3.99848784e-01,
       2.14463269e-01, 5.74997389e-01, 2.19568153e-01, 6.59127357e-01,
       8.68357453e-01, 8.22397773e-01, 8.11786432e-01, 3.54772745e-01,
       6.26505518e-01, 8.77898826e-01, 6.15694661e-01, 5.10110886e-01,
       7.67160774e-01, 8.57051061e-03, 6.43184510e-01, 8.66354707e-01,
       9.48544528e-01, 2.81336201e-01, 5.43657417e-01, 1.56600551e-01,
       9.29533562e-02, 3.95595045e-01, 6.25869951e-01, 1.36279637e-01,
       5.53282225e-01, 2.68100061e-01, 2.22157597e-01, 1.25920173e-01,
      

In [77]:
k=random.rand(5)

In [78]:
k

array([0.72079119, 0.3175225 , 0.73226323, 0.97718576, 0.5394719 ])

In [84]:
h=random.choice([12,23,435,552])
h

np.int64(23)